import java.util.Scanner;

/*To find the nth fibonacesi number. fibonacesi number is starts with 0 and 1 and next is generated by
  by adding the previous two numbers.*/

public class Febo {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int a = 0;
        int b = 1;
        int count=2;
        while (count<=n){
            int temp=b;
            b = b + a;
            a = temp;
            count++;
        }
        System.out.println(b);
    }
}
